name: npm-publish
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: npm-publish
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Publish to npm
        uses: pascalgn/npm-publish-action@1.1.0
